### PR TITLE
upgrade to grails 3.1.9

### PR DESCRIPTION
**Pull request by helgew**
The two commits only make minimal changes to the original source. Chiefly, they update the imports and convert the `doWithSpring` Closure to a method. Otherwise, files were moved to their new locations and the gradle build trimmings were added. 

I have tested the upgrade in an app and there are only a few modifications needed to publish it, I believe. However, if you are no longer maintaining the plugin, let me know and I'll be happy to take it on.

### CODE REVIEW

**Comment by ataylor284** [comment]
Thanks for the patch, but can you add back the grails wrapper?  TravisCI depends on it.

**Comment by helgew** [comment]
Sorry about the noise. Looks like it's working now.

**Comment by ataylor284** [comment]
Looks good!  Thanks for the pull request, I've been slow to move to grails 3.

**Comment by helgew** [comment]
You're welcome! Great plugin!

Any ETA on pushing it to the repository?

**Comment by ataylor284** [comment]
Pushed to bintray, and made the request to include it in the list of grails plugins.  It should be there shortly.

**Pull request merged**
